# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{db_rocket}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mauro Torres"]
  s.date = %q{2010-10-09}
  s.default_executable = %q{db_rocket}
  s.description = %q{Db Rocketa allows make your dump db very easy!}
  s.email = %q{maurotorres@gmail.com}
  s.executables = ["db_rocket"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/db_rocket.rb",
     "lib/db_rockets/cli/command.rb",
     "lib/db_rockets/cli/commands/app.rb",
     "lib/db_rockets/cli/commands/base.rb",
     "lib/db_rockets/cli/commands/help.rb",
     "lib/db_rockets/cli/commands/server.rb",
     "lib/db_rockets/cli/init.rb"
  ]
  s.homepage = %q{http://github.com/chebyte/db_rocket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{make your dump db very easy!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

